# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Week 0 project template

on:
  push:
    paths:
    - 'myPracticeCourseWork/_week_0/template_project/**'
  pull_request:
    paths:
    - 'myPracticeCourseWork/_week_0/template_project/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build week_0 template project with Maven 
      run: mvn -B package --file pom.xml
      working-directory: myPracticeCourseWork/_week_0/template_project
      
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: ^myPracticeCourseWork/_week_0/template_project/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
